Areas/Admin/Controllers/QLSachController.cs
using LeDangQuang_DoAnTotNghiep.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LeDangQuang_DoAnTotNghiep.Areas.Admin.Controllers
{
    public class QLSachController : Controller
    {
        DoAnDB db = new DoAnDB();
        // GET: Admin/QLSach
        public ActionResult Index()
        {
            var sach = db.Saches.Select(n => n);
            return View(sach);
        }
        public ActionResult ThemSach()
        {
            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM");
            ViewBag.MaTL = new SelectList(db.TheLoais, "MaTL", "TenTL");
            return View();
        }

        // POST: Admin/SACHes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemSach([Bind(Include = "MaSach,TenSach,SoLuong,Anh,MoTa,Gia,TacGia,MaTL,MaDM")] Sach sACH)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    sACH.Anh = "";
                    var f = Request.Files["Anhtg"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadPath = Server.MapPath("~/wwwroot/Images/" + FileName);
                        f.SaveAs(UploadPath);
                        sACH.Anh = FileName;
                    }
                    db.Saches.Add(sACH);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu " + ex.Message;
                ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sACH.MaDM);
                ViewBag.MaTL = new SelectList(db.TheLoais, "MaTL", "TenTL", sACH.MaTL);
                return View(sACH);
            }
        }

        public ActionResult SuaSach(int id)
        {
            Sach sACH = db.Saches.Find(id);
            if (sACH == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sACH.MaDM);
            ViewBag.MaTL = new SelectList(db.TheLoais, "MaTL", "TenTL", sACH.MaTL);
            return View(sACH);
        }

        // POST: Admin/SACHes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SuaSach([Bind(Include = "MaSach,TenSach,SoLuong,Anh,MoTa,Gia,TacGia,MaTL,MaDM")] Sach sACH)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var f = Request.Files["Anhtg"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadPath = Server.MapPath("~/wwwroot/Images/" + FileName);
                        f.SaveAs(UploadPath);
                        sACH.Anh = FileName;
                    }
                    db.Entry(sACH).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu " + ex.Message;
                ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sACH.MaDM);
                ViewBag.MaTL = new SelectList(db.TheLoais, "MaTL", "TenTL", sACH.MaTL);
                return View(sACH);
            }
        }

        [HttpDelete]
        public ActionResult XoaSach(int id)
        {
            var sach = db.Saches.Find(id);
            db.Saches.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Views/QLSach/Index.cshtml
@model IEnumerable<LeDangQuang_DoAnTotNghiep.Models.Sach>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section header{
    <div class="container-fluid px-4">
        <h1 class="mt-4" style="text-align: center;">Quản lý thông tin sách</h1>
    </div>
}
<p class="themmoibtn"><a href="@Url.Action("ThemSach","QLSach")" style="text-decoration: none; display: block; padding: 15px 25px;">Thêm sách</a></p>

<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Thông tin sách
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>Tên sách</th>
                    <th>Ảnh</th>
                    <th>Mô tả</th>
                    <th>Số lượng</th>
                    <th>Tác giả</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="row_@item.MaSach">
                        <td width="150px">
                            @Html.DisplayFor(modelItem => item.TenSach)
                        </td>
                        <td width="150px">
                            @{
                                string ImagePath = "~/wwwroot/Images/" + item.Anh;
                            }
                            <img src="@Url.Content(ImagePath)" width="150" />
                        </td>
                        <td width="400px">@Html.DisplayFor(modelItem => item.MoTa)</td>
                        <td width="150px">@Html.DisplayFor(modelItem => item.SoLuong)</td>
                        <td width="150px">@Html.DisplayFor(modelItem => item.TacGia)</td>
                        <td>
                            <p>
                                <a href="@Url.Action("SuaSach","QLSach",new { id = item.MaSach})" style="text-decoration: none;"><i class="fas fa-tools"></i> Sửa</a>
                            </p>
                            <p>
                                <i class="fas fa-trash-alt"></i>
                                @Ajax.ActionLink("Xóa", "XoaSach", new { id = item.MaSach },
                                    new AjaxOptions
                                         {
                                             Confirm = "Bạn có muốn xóa bản ghi này ?",
                                             OnComplete = "$('row_" + item.MaSach + "').remove()",
                                             HttpMethod = "Delete"
                                         })
                            </p>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

Areas/Admin/Views/QLSach/SuaSach.cshtml
@model LeDangQuang_DoAnTotNghiep.Models.Sach
@{
    ViewBag.Title = "SuaSach";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    string ImagePath = "~/wwwroot/Images/" + Model.Anh;
}

@section header{
    <div class="container-fluid px-4">
        <h1 class="mt-4" style="text-align: center;">Sửa sách</h1>
    </div>
}
@using (Html.BeginForm("SuaSach", "QLSach", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model=>model.MaSach)
    <table style="margin-left: 30%;">
        <tr>
            <td>
                <label for="dob_au">Thể loại</label>
            </td>
            <td>
                @Html.DropDownList("MaTL", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaTL, "", new { @class = "text-danger" })
            </td>
            <td rowspan="5">
                <label style="margin-left: 90px;">Ảnh</label>
                <br>
                <img id="output" width="150" height="150" style="border: solid 1px black; margin-left: 40px;" src="@Url.Content(ImagePath)"/>
                <br>
                <label for="image_au" style="margin-left: 40px; cursor:pointer">Chọn file ảnh</label>
                <input type="file" id="image_au" name="Anhtg" class="up_anh" onchange="loadFile(event)" style="margin-left: 20px; display:none">
                @Html.HiddenFor(model=>model.Anh)
            </td>
        </tr>

        <tr>
            <td>
                <label for="name_au">Danh mục</label>
            </td>
            <td>
                @Html.DropDownList("MaDM", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>
                <label for="hometown_au">Tên sách</label>
            </td>
            <td>
                @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>
                <label for="hometown_au">Tác giả</label>
            </td>
            <td>
                @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                <label for="ts_au">Mô tả</label>
            </td>
            <td>
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                <label for="ts_au">Số lượng</label>
            </td>
            <td>
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                <label for="ts_au">Giá bán</label>
            </td>
            <td>
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </td>
        </tr>
    </table>
    <br />
    <button style="margin-left: 27%; height: 40px; width: 200px; border-radius: 5px;
                                    font-size: 25px; background-color: #3399CC; color: black;">
        Lưu <i class="ti-check"></i>
    </button>
    <button style="margin-left:40px;height: 40px; width: 200px; border-radius: 5px;
                                    font-size: 25px; background-color: #3399CC; color: black;">
        <a href="@Url.Action("Index", "QLSach")" style="color:black; text-decoration:none;display:block">Hủy bỏ</a> <i class="ti-close"></i>
    </button>
}
@if (ViewBag.Error != null)
{
    <p class="alert alert-danger" role="alert">@ViewBag.Error</p>
}
<script>
    var loadFile = function (event) {
        image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>
<script src="~/Scripts/jquery.validate-vsdoc.js"></script>
<script src="~/Scripts/jquery-1.8.0.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

Areas/Admin/Views/QLSach/ThemSach.cshtml
@model LeDangQuang_DoAnTotNghiep.Models.Sach
@{
    ViewBag.Title = "ThemSach";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    <div class="container-fluid px-4">
        <h1 class="mt-4" style="text-align: center;">Thêm sách</h1>
    </div>
}
@using (Html.BeginForm("ThemSach", "QLSach", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<table style="margin-left: 30%;">
    <tr>
        <td>
            <label for="dob_au">Thể loại</label>
        </td>
        <td>
            @Html.DropDownList("MaTL", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaTL, "", new { @class = "text-danger" })
        </td>
        <td rowspan="5">
            <label style="margin-left: 90px;">Ảnh</label>
            <br>
            <img id="output" width="150" height="150" style="border: solid 1px black; margin-left: 40px;" />
            <br>
            <label for="image_au" style="margin-left: 40px; cursor:pointer">Chọn file ảnh</label>
            <input type="file" id="image_au" name="Anhtg" class="up_anh" onchange="loadFile(event)" style="margin-left: 20px; display:none">
        </td>
    </tr>

    <tr>
        <td>
            <label for="name_au">Danh mục</label>
        </td>
        <td>
            @Html.DropDownList("MaDM", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
        </td>
    </tr>

    <tr>
        <td>
            <label for="hometown_au">Tên sách</label>
        </td>
        <td>
            @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
        </td>
    </tr>

    <tr>
        <td>
            <label for="hometown_au">Tác giả</label>
        </td>
        <td>
            @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
        </td>
    </tr>
    <tr>
        <td>
            <label for="ts_au">Mô tả</label>
        </td>
        <td>
            @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </td>
    </tr>
    <tr>
        <td>
            <label for="ts_au">Số lượng</label>
        </td>
        <td>
            @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
        </td>
    </tr>
    <tr>
        <td>
            <label for="ts_au">Giá bán</label>
        </td>
        <td>
            @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
        </td>
    </tr>
</table>
    <br />
    <button style="margin-left: 27%; height: 40px; width: 200px; border-radius: 5px;
                                    font-size: 25px; background-color: #3399CC; color: black;">
        Tạo <i class="ti-check"></i>
    </button>
    <button style="margin-left:40px;height: 40px; width: 200px; border-radius: 5px;
                                    font-size: 25px; background-color: #3399CC; color: black;">
        <a href="@Url.Action("Index", "QLSach")" style="color:black; text-decoration:none;display:block">Hủy bỏ</a> <i class="ti-close"></i>
    </button>
}
@if (ViewBag.Error != null)
{
    <p class="alert alert-danger" role="alert">@ViewBag.Error</p>
}
<script>
    var loadFile = function (event) {
        image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>
<script src="~/Scripts/jquery.validate-vsdoc.js"></script>
<script src="~/Scripts/jquery-1.8.0.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>