Areas/Admin/Controllers/QLDonHangController.cs
using LeDangQuang_DoAnTotNghiep.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
namespace LeDangQuang_DoAnTotNghiep.Areas.Admin.Controllers
{
    public class QLDonHangController : Controller
    {
        DoAnDB db = new DoAnDB();
        // GET: Admin/QLDonHang
        public ActionResult Index()
        {
            var donhang = db.DonHangs.Where(n=>n.TrangThai == false).OrderBy(n=>n.NgayDat);
            return View(donhang);
        }
        public ActionResult XemChiTietDonHang(int id)
        {
            var chitiet = db.ChiTietDonHangs.Where(n => n.MaDonHang.Equals(id)).Select(n => n);
            ViewBag.TongTien = chitiet.Sum(n => n.GiaBan * n.SoLuong);
            ViewBag.TongTien = Convert.ToInt32(ViewBag.TongTien);
            return View(chitiet);
        }
        public ActionResult GiaoChoDVVanChuyen()
        {
            var dagiao = db.DonHangs.Where(n=>n.TrangThai == true && n.DaGiao == false).OrderBy(n=>n.NgayDat);
            return View(dagiao);
        }
        public ActionResult DonBiHuy()
        {
            var dagiao = db.DonHangs.Where(n => n.TrangThai == true && n.DaHuy == true).OrderBy(n => n.NgayDat);
            return View(dagiao);
        }
        public ActionResult DonThanhToan()
        {
            var dagiao = db.DonHangs.Where(n => n.TrangThai == true && n.DaGiao == true).OrderBy(n => n.NgayDat);
            return View(dagiao);
        }
        public ActionResult DaThanhToan(int id)
        {
            DonHang dh = db.DonHangs.Single(n => n.MaDonHang.Equals(id));
            dh.DaThanhToan = true;
            db.SaveChanges();
            GuiEmail("Xác nhận đơn hàng", "ledangquang443@gmail.com", "bookshoplequang@gmail.com", "Quang123google", "Đơn hàng của đã được thanh toán. Cảm ơn bạn vì đã tin tưởng chúng tôi !!");
            return RedirectToAction("DonThanhToan");
        }
        public ActionResult DaGiao(int id)
        {
            DonHang dh = db.DonHangs.SingleOrDefault(n => n.MaDonHang.Equals(id));
            dh.DaGiao = true;
            db.SaveChanges();
            GuiEmail("Xác nhận đơn hàng", "ledangquang443@gmail.com", "bookshoplequang@gmail.com", "Quang123google", "Đơn hàng của bạn đã được nhà sách Việt Lý" +
                "giao cho đơn vị vận chuyển. Sau khi nhận được hàng, quý khách vui lòng đăng nhập vào website bằng email đăng ký, mật khẩu" +
                "là: 123456, chọn mục: Đơn hàng của tôi và bấm vào nút Đã nhận để thành toán. Xin cảm ơn!");
            return RedirectToAction("GiaoChoDVVanChuyen");
        }
        public ActionResult DuyetDonHang(int id)
        {
            DonHang dh = db.DonHangs.Single(n => n.MaDonHang.Equals(id));
            dh.TrangThai = true;
            db.SaveChanges();
            GuiEmail("Xác nhận đơn hàng", "ledangquang443@gmail.com", "bookshoplequang@gmail.com", "Quang123google", "Đơn hàng của bạn đã được duyệt. Cảm ơn bạn vì đã tin tưởng chúng tôi !!");
            return RedirectToAction("Index");
        }
        public void GuiEmail(string title, string toEmail,string fromEmail,string Password, string Content)
        {
            MailMessage mail = new MailMessage();
            mail.To.Add(toEmail);
            mail.From = new MailAddress(toEmail);
            mail.Subject = title;
            mail.Body = Content;
            mail.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new System.Net.NetworkCredential(fromEmail, Password);
            smtp.EnableSsl = true;
            smtp.Send(mail);
        }
    }
}

Areas/Admin/Views/QLDonHang/DonBiHuy.cshtml
@model IEnumerable<LeDangQuang_DoAnTotNghiep.Models.DonHang>
@{
    ViewBag.Title = "DonBiHuy";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section header{
    <div class="container-fluid px-4">
        <h1 class="mt-4" style="text-align: center;">Đơn hàng bị hủy</h1>
    </div>
}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Thông tin đơn hàng
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>Tên khách hàng</th>
                    <th>Ngày đặt</th>
                    <th>Số điện thoại</th>
                    <th>Địa chỉ nhận</th>
                    <th>Trạng thái</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.KhachHang.HoTen</td>
                        <td>@item.NgayDat</td>
                        <td>@item.KhachHang.SoDT</td>
                        <td>@item.DiaChiNhan</td>
                        <td>@(item.DaHuy.Equals(true) ? "Đã hủy":"Chưa hủy")</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <p><a href="@Url.Action("Index","QLDonHang")" style="float: right; padding: 10px 15px; border: 1px solid #0d6efd; background-color: #0d6efd; border-radius: 5px; color: white; text-decoration:none; margin-right: 20px ">Quay lại</a></p>
</div>

Areas/Admin/Views/QLDonHang/DonThanhToan.cshtml
@model IEnumerable<LeDangQuang_DoAnTotNghiep.Models.DonHang>
@{
    ViewBag.Title = "DonThanhToan";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    <div class="container-fluid px-4">
        <h1 class="mt-4" style="text-align: center;">Quản lý đơn hàng</h1>
    </div>
}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Thông tin đơn hàng
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>Tên khách hàng</th>
                    <th>Ngày đặt</th>
                    <th>Số điện thoại</th>
                    <th>Địa chỉ nhận</th>
                    <th>Trạng thái</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.KhachHang.HoTen</td>
                        <td>@item.NgayDat</td>
                        <td>@item.KhachHang.SoDT</td>
                        <td>@item.DiaChiNhan</td>
                        <td>@(item.DaThanhToan == false ? "Chưa thanh toán" : "Đã thanh toán")</td>
                        <td style="display:flex; justify-content: space-around">
                            <a href="@Url.Action("DaThanhToan","QLDonHang",new {id = item.MaDonHang })" style="text-decoration:none">Xác nhận thanh toán</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <p><a href="@Url.Action("Index","QLDonHang")" style="float: right; padding: 10px 15px; border: 1px solid #0d6efd; background-color: #0d6efd; border-radius: 5px; color: white; text-decoration:none; margin-right: 20px ">Quay lại</a></p>
</div>

Areas/Admin/Views/QLDonHang/GiaoChoDVVanChuyen.cshtml
@model IEnumerable<LeDangQuang_DoAnTotNghiep.Models.DonHang>
@{
    ViewBag.Title = "GiaoChoDVVanChuyen";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    <div class="container-fluid px-4">
        <h1 class="mt-4" style="text-align: center;">Đơn hàng đã giao</h1>
    </div>
}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Thông tin đơn hàng
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>Tên khách hàng</th>
                    <th>Ngày đặt</th>
                    <th>Số điện thoại</th>
                    <th>Địa chỉ nhận</th>
                    <th>Đã giao</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.KhachHang.HoTen</td>
                        <td>@item.NgayDat</td>
                        <td>@item.KhachHang.SoDT</td>
                        <td>@item.DiaChiNhan</td>
                        <td>@(item.DaGiao == false ? "Chưa giao" : "Đã giao")</td>
                        <td style="display:flex; justify-content: space-around">
                            <a href="@Url.Action("DaGiao","QLDonHang",new {id = item.MaDonHang })" style="text-decoration:none">Xác nhận giao</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <p><a href="@Url.Action("Index","QLDonHang")" style="float: right; padding: 10px 15px; border: 1px solid #0d6efd; background-color: #0d6efd; border-radius: 5px; color: white; text-decoration:none; margin-right: 20px ">Quay lại</a></p>
</div>

Areas/Admin/Views/QLDonHang/Index.cshtml
@model IEnumerable<LeDangQuang_DoAnTotNghiep.Models.DonHang>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    <div class="container-fluid px-4">
        <h1 class="mt-4" style="text-align: center;">Quản lý đơn hàng</h1>
    </div>
}
<div style="display:flex; justify-content: space-around; height:50px; align-items:center; margin-bottom:10px">
    <a href="@Url.Action("DonThanhToan","QLDonHang")" style="text-decoration: none; padding: 10px 20px; border: 1px solid #0d6efd; border-radius: 5px; background-color: #0d6efd; color:white ">Đã thanh toán</a>
    <a href="@Url.Action("GiaoChoDVVanChuyen","QLDonHang")" style="text-decoration: none; padding: 10px 20px; border: 1px solid #0d6efd; border-radius: 5px; background-color: #0d6efd; color:white ">Giao cho đơn vị vận chuyển</a>
    <a href="@Url.Action("DonBiHuy","QLDonHang")" style="text-decoration: none; padding: 10px 20px; border: 1px solid #0d6efd; border-radius: 5px; background-color: #0d6efd; color:white ">Đã hủy</a>
</div>
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Thông tin đơn hàng
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>Tên khách hàng</th>
                    <th>Ngày đặt</th>
                    <th>Số điện thoại</th>
                    <th>Địa chỉ nhận</th>
                    <th>Trạng thái</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.KhachHang.HoTen</td>
                    <td>@item.NgayDat</td>
                    <td>@item.KhachHang.SoDT</td>
                    <td>@item.DiaChiNhan</td>
                    <td>@(item.TrangThai == false ? "Chưa duyệt" : "Đã duyệt")</td>
                    <td style="display:flex; justify-content: space-around">
                        @if(item.TrangThai == false)
                        {
                        <a href="@Url.Action("DuyetDonHang","QLDonHang",new {id = item.MaDonHang })" style="text-decoration:none">Duyệt đơn</a>
                        }               
                        <a href="@Url.Action("XemChiTietDonHang","QLDonHang",new {id = item.MaDonHang })" style="text-decoration:none">Chi tiết</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Areas/Admin/Views/QLDonHang/XemChiTietDonHang.cshtml
@model IEnumerable<LeDangQuang_DoAnTotNghiep.Models.ChiTietDonHang>
@{
    ViewBag.Title = "XemChiTietDonHang";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    <div class="container-fluid px-4">
        <h1 class="mt-4" style="text-align: center;">Quản lý đơn hàng</h1>
    </div>
}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Thông tin danh mục
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>Tên sách</th>
                    <th>Số lượng</th>
                    <th>Giá bán</th>
                    <th>Thành tiền</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Sach.TenSach</td>
                        <td>@item.SoLuong</td>
                        <td>@(Convert.ToInt32(item.GiaBan)) VNĐ</td>
                        <td>@(Convert.ToInt32(item.GiaBan) * item.SoLuong) VNĐ</td>
                    </tr>
                }
                <tr>
                    <td>Tổng tiền</td>
                    <td colspan="3" style="text-align:right">@ViewBag.TongTien VNĐ</td>
                </tr>
            </tbody>

        </table>
    </div>
    <div style="display:flex; flex; justify-content:space-around">
        <button style="border: 1px solid #0d6efd; border-radius: 4px; color: white; background-color: #0d6efd; width:98px" id="btnInDonHang">In hóa đơn</button>
        <a href="@Url.Action("Index","QLDonHang")" style="text-decoration: none; padding: 10px 20px; border: 1px solid #0d6efd; border-radius: 4px; color: white; background-color: #0d6efd ">Quay lại</a>
    </div>
</div>

<script>
    $("#btnInDonHang").click(function () {
        var content = $("#datatablesSimple").html();
        InDonHang(content);
    });

    function InDonHang(content) {
        var printWindow = window.open('', '', 'height = 400, width=800');
        printWindow.document.write('<html><head><title>In Hóa Đơn</title>');
        printWindow.document.write('</head><body>');
        printWindow.document.write('<table>');
        printWindow.document.write(content);
        printWindow.document.write('</table>');
        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.print();
    }
</script>