Areas/Admin/Controllers/QLNhanVienController.cs
using LeDangQuang_DoAnTotNghiep.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeDangQuang_DoAnTotNghiep.Areas.Admin.Controllers
{
    public class QLNhanVienController : Controller
    {
        DoAnDB db = new DoAnDB();
        // GET: Admin/QLNhanVien
        public ActionResult Index()
        {
            var nhanvien = db.NhanViens.Select(n => n);
            return View(nhanvien);
        }
        [HttpGet]
        public ActionResult ThemNV()
        {
            ViewBag.MaQuyen = new SelectList(db.Quyens, "MaQuyen", "TenQuyen");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemNV([Bind(Include = "MaNV,MaQuyen,HoTen,DiaChi,Email,SoDT,MatKhau")] NhanVien nhanVien)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.NhanViens.Add(nhanVien);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu " + ex.Message;
                ViewBag.MaQuyen = new SelectList(db.Quyens, "MaQuyen", "TenQuyen");
                return View(nhanVien);
            }
        }
        [HttpGet]
        public ActionResult SuaNV(int id)
        {
            NhanVien nhanVien = db.NhanViens.Find(id);
            ViewBag.MaQuyen = new SelectList(db.Quyens, "MaQuyen", "TenQuyen");
            return View(nhanVien);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SuaNV([Bind(Include = "MaNV,MaQuyen,HoTen,DiaChi,Email,SoDT,MatKhau")] NhanVien nhanVien)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(nhanVien).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu " + ex.Message;
                ViewBag.MaQuyen = new SelectList(db.Quyens, "MaQuyen", "TenQuyen");
                return View(nhanVien);
            }
        }

        [HttpDelete]
        public ActionResult XoaNV(int id)
        {
            var nhanVien = db.NhanViens.Find(id);
            db.NhanViens.Remove(nhanVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Views/QLNhanVien/Index.cshtml
@model IEnumerable<LeDangQuang_DoAnTotNghiep.Models.NhanVien>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section header{
    <div class="container-fluid px-4">
        <h1 class="mt-4" style="text-align: center;">Quản lý nhân viên</h1>
    </div>
}
<p class="themmoibtn"><a href="@Url.Action("ThemNV","QLNhanVien")" style="text-decoration: none; display: block; padding: 15px 25px;">Thêm nhân viên</a></p>
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Thông tin sách
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>Mã nhân viên</th>
                    <th>Tên nhân viên</th>
                    <th>Chức vụ</th>
                    <th>Địa chỉ</th>
                    <th>Email</th>
                    <th>Số điện thoại</th>
                    <th>Mật khẩu</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="row_@item.MaNV">
                        <td width="150px">@Html.DisplayFor(modelItem => item.MaNV)</td>
                        <td width="150px">
                            @Html.DisplayFor(modelItem => item.HoTen)
                        </td>

                        <td>
                            @item.Quyen.TenQuyen
                        </td>
                        <td width="200px">@Html.DisplayFor(modelItem => item.DiaChi)</td>
                        <td width="150px">@Html.DisplayFor(modelItem => item.Email)</td>
                        <td width="150px">@Html.DisplayFor(modelItem => item.SoDT)</td>
                        <td>@item.MatKhau</td>
                        <td>
                            <p>
                                <a href="@Url.Action("SuaNV","QLNhanVien",new { id = item.MaNV})" style="text-decoration: none;"><i class="fas fa-tools"></i> Sửa</a>
                            </p>
                            <p>
                                <i class="fas fa-trash-alt"></i>
                                @Ajax.ActionLink("Xóa", "XoaNV", new { id = item.MaNV },
                                    new AjaxOptions
                                         {
                                             Confirm = "Bạn có muốn xóa bản ghi này ?",
                                        OnComplete = "$('row_" + item.MaNV + "').remove()",
                                        HttpMethod = "Delete"
                                         })
                            </p>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

Areas/Admin/Views/QLNhanVien/SuaNV.cshtml
@model LeDangQuang_DoAnTotNghiep.Models.NhanVien
@{
    ViewBag.Title = "SuaNV";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section header{
    <div class="container-fluid px-4">
        <h1 class="mt-4" style="text-align: center;">Sửa nhân viên</h1>
    </div>
}
@using (Html.BeginForm("SuaNV", "QLNhanVien", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaNV)
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Thông tin sách
    </div>
    <div class="card-body">
        <table style="margin-left: 30%;">
            <tr>
                <td>
                    <label for="dob_au">Chức vụ</label>
                </td>
                <td>
                    @Html.DropDownList("MaQuyen", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaQuyen, "", new { @class = "text-danger" })
                </td>
            </tr>

            <tr>
                <td>
                    <label for="name_au">Tên nhân viên</label>
                </td>
                <td>
                    @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
                </td>
            </tr>

            <tr>
                <td>
                    <label for="name_au">Địa chỉ</label>
                </td>
                <td>
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </td>
            </tr>

            <tr>
                <td>
                    <label for="name_au">Email</label>
                </td>
                <td>
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </td>
            </tr>

            <tr>
                <td>
                    <label for="hometown_au">Số điện thoại</label>
                </td>
                <td>
                    @Html.EditorFor(model => model.SoDT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoDT, "", new { @class = "text-danger" })
                </td>
            </tr>

            <tr>
                <td>
                    <label for="ts_au">Mật khẩu</label>
                </td>
                <td>
                    @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                </td>
            </tr>
        </table>
        <br />
        <button style="margin-left: 27%; height: 40px; width: 200px; border-radius: 5px;
                                    font-size: 25px; background-color: #3399CC; color: black;">
            Lưu <i class="ti-check"></i>
        </button>
        <button style="margin-left:40px;height: 40px; width: 200px; border-radius: 5px;
                                    font-size: 25px; background-color: #3399CC; color: black;">
            <a href="@Url.Action("Index", "QLNhanVien")" style="color:black; text-decoration:none;display:block">Hủy bỏ</a> <i class="ti-close"></i>
        </button>
        </div>
    </div>
        }
        @if (ViewBag.Error != null)
        {
            <p class="alert alert-danger" role="alert">@ViewBag.Error</p>
        }
        <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
        <script src="~/Scripts/jquery-1.8.0.min.js"></script>
        <script src="~/Scripts/jquery.validate.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

Areas/Admin/Views/QLNhanVien/ThemNV.cshtml
@model LeDangQuang_DoAnTotNghiep.Models.NhanVien
@{
    ViewBag.Title = "ThemNV";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section header{
    <div class="container-fluid px-4">
        <h1 class="mt-4" style="text-align: center;">Thêm nhân viên</h1>
    </div>
}
@using (Html.BeginForm("ThemNV", "QLNhanVien", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Thông tin nhân viên
        </div>
        <div class="card-body">
            <table style="margin-left: 30%;">
                <tr>
                    <td>
                        <label for="dob_au">Chức vụ</label>
                    </td>
                    <td>
                        @Html.DropDownList("MaQuyen", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaQuyen, "", new { @class = "text-danger" })
                    </td>
                </tr>

                <tr>
                    <td>
                        <label for="name_au">Tên nhân viên</label>
                    </td>
                    <td>
                        @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
                    </td>
                </tr>

                <tr>
                    <td>
                        <label for="name_au">Địa chỉ</label>
                    </td>
                    <td>
                        @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                    </td>
                </tr>

                <tr>
                    <td>
                        <label for="name_au">Email</label>
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </td>
                </tr>

                <tr>
                    <td>
                        <label for="hometown_au">Số điện thoại</label>
                    </td>
                    <td>
                        @Html.EditorFor(model => model.SoDT, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SoDT, "", new { @class = "text-danger" })
                    </td>
                </tr>

                <tr>
                    <td>
                        <label for="ts_au">Mật khẩu</label>
                    </td>
                    <td>
                        @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                    </td>
                </tr>
            </table>

            <br />
            <button style="margin-left: 27%; height: 40px; width: 200px; border-radius: 5px;
                                    font-size: 25px; background-color: #3399CC; color: black;">
                Tạo <i class="ti-check"></i>
            </button>
            <button style="margin-left:40px;height: 40px; width: 200px; border-radius: 5px;
                                    font-size: 25px; background-color: #3399CC; color: black;">
                <a href="@Url.Action("Index", "QLNhanVien")" style="color:black; text-decoration:none;display:block">Hủy bỏ</a> <i class="ti-close"></i>
            </button>
        </div>
    </div>
}
@if (ViewBag.Error != null)
{
    <p class="alert alert-danger" role="alert">@ViewBag.Error</p>
}
<script src="~/Scripts/jquery.validate-vsdoc.js"></script>
<script src="~/Scripts/jquery-1.8.0.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>